import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,modal
}: Readonly<{
  children: React.ReactNode,modal:ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head> link... </head> */}
      <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossOrigin="anonymous"></link>
      </head>
      
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Link href='/'>Home</Link>
        <Link href='/store'>store</Link>
        <Link href='/login'>login</Link>
        <Link href='/about'>about</Link>
        <div className="border border-success border border-5">
          {children}
        </div>
        <div>
          
        </div>
        <div className="border border-danger border border-5">
          {modal}
        </div>
        
      </body>
    </html>
  );
}
